# Generated by Django 5.2 on 2025-05-26 14:02

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.variation_image_upload_to),
        ),
    ]
