# Generated by Django 5.2 on 2025-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_customer_type_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('customer', 'Customer')], max_length=10),
        ),
    ]
